# Generated by Django 5.2.10 on 2026-01-30 09:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('avg_temperature', models.FloatField()),
                ('budget_per_day_usd', models.FloatField()),
                ('safety_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('popularity_score', models.FloatField(default=5.0)),
                ('beach', models.FloatField(default=0.5)),
                ('mountain', models.FloatField(default=0.5)),
                ('culture', models.FloatField(default=0.5)),
                ('adventure', models.FloatField(default=0.5)),
                ('nightlife', models.FloatField(default=0.5)),
                ('shopping', models.FloatField(default=0.5)),
                ('nature', models.FloatField(default=0.5)),
                ('historical', models.FloatField(default=0.5)),
                ('family_friendly', models.FloatField(default=0.5)),
                ('romantic', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('relevance_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomenderApp.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recomenderApp.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_max', models.FloatField(default=2000)),
                ('min_safety_score', models.FloatField(default=7.0)),
                ('preferred_temperature', models.FloatField(default=22.0)),
                ('beach_preference', models.FloatField(default=0.5)),
                ('culture_preference', models.FloatField(default=0.5)),
                ('adventure_preference', models.FloatField(default=0.5)),
                ('nature_preference', models.FloatField(default=0.5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
