# Generated by Django 5.2.10 on 2026-01-30 11:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomenderApp', '0002_alter_userpreference_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='adventure_preference',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='beach_preference',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='culture_preference',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='min_safety_score',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='nature_preference',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_temperature',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='adventure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='avg_temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='beach',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='budget_per_day_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2026, 1, 30)),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='culture',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='family_friendly',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='historical',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='mountain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='nature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='nightlife',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='romantic',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='safety_score',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='shopping',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
